{
 "title": "Grafana Grotrack",
 "time": { "from": "2025-08-30T12:00:00.000Z", "to": "2026-08-30T11:59:59.999Z" },
 "panels": [
  {
   "title": "Faturamento Mensal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "grotrack",
     "rawSql": "SELECT \n    CAST(DATE_FORMAT(data_atualizacao, '%Y-%m-01') AS DATETIME) AS time,\n    SUM(valor_total) AS faturamento\nFROM ordem_de_servicos\nWHERE ativo = 1\nGROUP BY time\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Quantidade de OS por Status",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "grotrack",
     "rawSql": "SELECT \n    status, \n    COUNT(*) AS quantidade\nFROM ordem_de_servicos\nWHERE ativo = 1\nGROUP BY status;"
    }
   ]
  },
  {
   "title": "TOP 5 OS maior gasto",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "grotrack",
     "rawSql": "SELECT \n    id_ordem_servico AS id_ordem_servico, \n    valor_total \nFROM ordem_de_servicos\nWHERE ativo = 1\nORDER BY valor_total DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Ticket Médio Gasto na Oficina",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grotrack",
     "rawSql": "SELECT \n    AVG(valor_total) AS ticket_medio\nFROM ordem_de_servicos\nWHERE ativo = 1 AND status = 'FINALIZADO';"
    }
   ]
  },
  {
   "title": "Top 5 Produtos mais vendidos",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "grotrack",
     "rawSql": "SELECT \n    p.nome AS produto, \n    SUM(ip.quantidade) AS total_vendido\nFROM itens_produtos ip\nJOIN produtos p ON ip.fk_produto = p.id_produto\nGROUP BY p.id_produto, p.nome\nORDER BY total_vendido DESC\nLIMIT 5;"
    }
   ]
  }
 ]
}